name: CSDN Hotter

on:
  workflow_dispatch:
  schedule:
    - cron: "* */3 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    # Service containers to run with `runner-job`
    services:
      # Label used to access the service container
      redis:
        # Docker Hub image
        image: redis
      pool:
        # Docker Hub image
        image: germey/proxypool

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Setup Python
        uses: actions/setup-python@v2.3.2
        with:
          python-version: "3.8"
          architecture: "x64"

      # Install docker-compose and drivers
      - name: Install scripts
        run: sh ./scripts/install.sh

      # Start the containers in the background
      - name: Install environments
        run: docker-compose up -d

      # Install requirement packages
      - name: Install packages
        run: pip install -r requirements.txt

      # Run main
      - name: Run application
        env:
          USERNAME: ${{ secrets.USERNAME }}
          MODE: ${{ secrets.MODE }}
        run: python -u main.py
        